# Generated by Django 4.0.4 on 2022-06-06 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('Motivational', 'Motivational'), ('Biography', 'Biography'), ('Autobiography', 'Autobiography'), ('Kids', 'Kids'), ('Entertainment', 'Entertainment'), ('Other', 'Other')], max_length=15)),
            ],
            options={
                'db_table': 'book_data',
            },
        ),
        migrations.CreateModel(
            name='LoginInfo_Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=20, unique=True)),
                ('passwd', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'Login_Info',
                'unique_together': {('email', 'passwd')},
            },
        ),
    ]
